"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowRight, ArrowUpRight, CircleDollarSign, Package, ReceiptText, WalletCards } from "lucide-react";
import { categories, getDashboardMetrics } from "@/lib/demo-data";
import { formatCurrency, formatDate, formatNumber } from "@/lib/format";
import type { DashboardFilters } from "@/lib/types";

interface DashboardProps { demo?: boolean }

export function Dashboard({ demo = false }: DashboardProps) {
  const [filters, setFilters] = useState<DashboardFilters>({ period: 30, category: "Semua kategori" });
  const metrics = useMemo(() => getDashboardMetrics(filters), [filters]);
  const chartData = filters.period === 90 ? metrics.daily.filter((_, index) => index % 5 === 0 || index === metrics.daily.length - 1) : metrics.daily;
  const topProducts = metrics.productSales.slice(0, 5);

  return (
    <div className="mx-auto max-w-[1400px]">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">Ringkasan bisnis</h1>{demo && <span className="badge bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300">Mode demo</span>}</div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Selasa, 8 September 2026 · Toko Rasa Kita</p></div><div className="grid grid-cols-2 gap-2 sm:flex"><select aria-label="Pilih periode" className="input min-w-0 sm:w-40" value={filters.period} onChange={(event) => setFilters((current) => ({ ...current, period: Number(event.target.value) as DashboardFilters["period"] }))}><option value={7}>7 hari terakhir</option><option value={30}>30 hari terakhir</option><option value={90}>90 hari terakhir</option></select><select aria-label="Pilih kategori" className="input min-w-0 sm:w-44" value={filters.category} onChange={(event) => setFilters((current) => ({ ...current, category: event.target.value }))}>{categories.map((category) => <option key={category}>{category}</option>)}</select></div></div>
      <div className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard icon={WalletCards} label="Omzet" value={formatCurrency(metrics.revenue, true)} change="12,4%" tone="indigo" /><MetricCard icon={CircleDollarSign} label="Laba kotor" value={formatCurrency(metrics.profit, true)} change="9,8%" tone="emerald" /><MetricCard icon={ReceiptText} label="Transaksi" value={formatNumber(metrics.completedCount)} change="6,2%" tone="amber" /><MetricCard icon={Package} label="Produk terjual" value={formatNumber(metrics.units)} change="14,1%" tone="sky" /></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.7fr_1fr]"><section className="card min-w-0 p-4 sm:p-5" aria-labelledby="revenue-chart"><div className="flex items-start justify-between"><div><h2 id="revenue-chart" className="font-extrabold text-slate-950 dark:text-white">Tren omzet dan laba</h2><p className="mt-1 text-xs text-slate-500">Performa pada periode terpilih</p></div><div className="hidden gap-3 text-[10px] font-bold text-slate-500 sm:flex"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-indigo-500" />Omzet</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-emerald-500" />Laba</span></div></div><div className="mt-5 h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 5, right: 5, left: -20, bottom: 0 }}><defs><linearGradient id="omzet" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#6366f1" stopOpacity={0.28}/><stop offset="95%" stopColor="#6366f1" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="#cbd5e1" opacity={0.35}/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 10 }} minTickGap={25}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 10 }} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`}/><Tooltip content={<ChartTooltip />} /><Area type="monotone" dataKey="omzet" stroke="#6366f1" strokeWidth={2.5} fill="url(#omzet)" /><Area type="monotone" dataKey="laba" stroke="#10b981" strokeWidth={2} fill="transparent" /></AreaChart></ResponsiveContainer></div></section><section className="card min-w-0 p-4 sm:p-5" aria-labelledby="category-chart"><h2 id="category-chart" className="font-extrabold text-slate-950 dark:text-white">Kontribusi kategori</h2><p className="mt-1 text-xs text-slate-500">Berdasarkan omzet</p><div className="mt-2 h-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={metrics.categories} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={48} outerRadius={72} paddingAngle={3}>{metrics.categories.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={(value) => formatCurrency(Number(value))} /></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-x-3 gap-y-2">{metrics.categories.slice(0,4).map((item) => <div key={item.name} className="flex min-w-0 items-center gap-2 text-xs"><span className="size-2 shrink-0 rounded-full" style={{ background: item.color }} /><span className="truncate text-slate-500">{item.name}</span></div>)}</div></section></div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_1fr]"><section className="card min-w-0 p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-slate-950 dark:text-white">Produk terlaris</h2><p className="mt-1 text-xs text-slate-500">Urutan berdasarkan omzet</p></div></div><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={topProducts} layout="vertical" margin={{ left: -16, right: 12 }}><CartesianGrid strokeDasharray="4 4" horizontal={false} stroke="#cbd5e1" opacity={0.35}/><XAxis type="number" axisLine={false} tickLine={false} tick={{ fill: "#94a3b8", fontSize: 10 }} tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`}/><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} width={112} tick={{ fill: "#64748b", fontSize: 10 }}/><Tooltip formatter={(value) => formatCurrency(Number(value))}/><Bar dataKey="revenue" radius={[0, 6, 6, 0]}>{topProducts.map((item) => <Cell key={item.sku} fill={item.color}/>)}</Bar></BarChart></ResponsiveContainer></div></section><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-4 sm:p-5 dark:border-slate-800"><div><h2 className="font-extrabold text-slate-950 dark:text-white">Transaksi terbaru</h2><p className="mt-1 text-xs text-slate-500">Aktivitas pada periode ini</p></div><Link href={demo ? "/demo#transaksi" : "/app/transaksi"} className="text-xs font-extrabold text-indigo-600 hover:underline dark:text-indigo-400">Lihat semua</Link></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{metrics.transactions.slice(0,5).map((item) => <div key={item.id} className="flex items-center gap-3 p-3.5 sm:px-5"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-800"><ReceiptText className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-extrabold text-slate-900 dark:text-white">{item.productName}</p><p className="mt-1 text-[10px] text-slate-500">{formatDate(item.date, true)} · {item.channel}</p></div><div className="text-right"><p className="text-xs font-extrabold text-slate-900 dark:text-white">{formatCurrency(item.total)}</p><p className="mt-1 text-[10px] text-emerald-600">Selesai</p></div></div>)}</div></section></div>
      {demo && <div className="mt-6 flex flex-col items-start justify-between gap-4 rounded-2xl border border-indigo-200 bg-indigo-50 p-5 sm:flex-row sm:items-center dark:border-indigo-900 dark:bg-indigo-950/40"><div><h2 className="font-extrabold text-indigo-950 dark:text-indigo-100">Suka dengan yang Anda lihat?</h2><p className="mt-1 text-sm text-indigo-700 dark:text-indigo-300">Gunakan data bisnis Anda sendiri dan dapatkan wawasan serupa.</p></div><Link href="/daftar" className="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-indigo-600 px-5 text-sm font-extrabold text-white hover:bg-indigo-700">Buat akun gratis <ArrowRight className="size-4" /></Link></div>}
    </div>
  );
}

function MetricCard({ icon: Icon, label, value, change, tone }: { icon: typeof WalletCards; label: string; value: string; change: string; tone: "indigo" | "emerald" | "amber" | "sky" }) {
  const tones = { indigo: "bg-indigo-50 text-indigo-600 dark:bg-indigo-950/50 dark:text-indigo-300", emerald: "bg-emerald-50 text-emerald-600 dark:bg-emerald-950/50 dark:text-emerald-300", amber: "bg-amber-50 text-amber-600 dark:bg-amber-950/50 dark:text-amber-300", sky: "bg-sky-50 text-sky-600 dark:bg-sky-950/50 dark:text-sky-300" };
  return <article className="card min-w-0 p-3.5 sm:p-5"><div className="flex items-start justify-between gap-2"><div className={`grid size-9 shrink-0 place-items-center rounded-xl sm:size-10 ${tones[tone]}`}><Icon className="size-[18px]" /></div><span className="hidden items-center gap-1 text-[10px] font-extrabold text-emerald-600 sm:flex"><ArrowUpRight className="size-3" />{change}</span></div><p className="mt-4 text-[11px] font-bold text-slate-500 sm:text-xs">{label}</p><p className="mt-1 truncate text-lg font-black tracking-tight text-slate-950 dark:text-white sm:text-2xl">{value}</p><p className="mt-1 flex items-center gap-1 text-[9px] font-bold text-emerald-600 sm:hidden"><ArrowUpRight className="size-3" />{change}</p></article>;
}

function ChartTooltip({ active, payload, label }: { active?: boolean; payload?: ReadonlyArray<{ name?: string; value?: number; color?: string }>; label?: string }) {
  if (!active || !payload?.length) return null;
  return <div className="rounded-xl border border-slate-200 bg-white p-3 text-xs shadow-xl dark:border-slate-700 dark:bg-slate-900"><p className="mb-2 font-extrabold text-slate-900 dark:text-white">{label}</p>{payload.map((item) => <p key={item.name} className="mt-1 flex items-center justify-between gap-6 text-slate-500"><span>{item.name === "omzet" ? "Omzet" : "Laba"}</span><strong style={{ color: item.color }}>{formatCurrency(Number(item.value))}</strong></p>)}</div>;
}
