"use client";

import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowLeft, Boxes, CircleDollarSign, PackageCheck, ShoppingBag, TrendingUp } from "lucide-react";
import Link from "next/link";
import type { Product, Transaction } from "@/lib/types";
import { formatCurrency, formatDate, formatNumber } from "@/lib/format";

export function ProductDetail({ product, transactions, backHref }: { product: Product; transactions: Transaction[]; backHref?: string }) {
  const resolvedBackHref = backHref ?? "/app/transaksi";
  const sales = transactions.filter((item) => item.type === "Penjualan" && item.status === "Selesai");
  const revenue = sales.reduce((sum, item) => sum + item.total, 0);
  const units = sales.reduce((sum, item) => sum + item.quantity, 0);
  const profit = sales.reduce((sum, item) => sum + (item.unitPrice - product.cost) * item.quantity, 0);
  const trend = [...sales].reverse().slice(-24).map((item) => ({ date: new Intl.DateTimeFormat("id-ID", { day: "numeric", month: "short", timeZone: "Asia/Jakarta" }).format(new Date(item.date)), omzet: item.total }));
  return <div className="mx-auto max-w-[1200px]"><Link href={resolvedBackHref} className="inline-flex min-h-10 items-center gap-2 text-xs font-extrabold text-slate-500 hover:text-indigo-600"><ArrowLeft className="size-4" /> Kembali ke transaksi</Link><div className="mt-3 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex min-w-0 items-center gap-4"><div className="grid size-14 shrink-0 place-items-center rounded-2xl text-white" style={{ background: product.color }}><ShoppingBag className="size-6" /></div><div className="min-w-0"><p className="text-xs font-extrabold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">{product.category} · {product.sku}</p><h1 className="mt-1 truncate text-2xl font-black tracking-tight text-slate-950 dark:text-white sm:text-3xl">{product.name}</h1></div></div><span className={`badge ${product.stock <= product.reorderPoint ? "bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300" : "bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"}`}>{product.stock <= product.reorderPoint ? <AlertTriangle className="size-3" /> : <PackageCheck className="size-3" />}{product.stock <= product.reorderPoint ? "Stok perlu diisi" : "Stok aman"}</span></div>
    <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={CircleDollarSign} label="Omzet 90 hari" value={formatCurrency(revenue, true)} /><Stat icon={TrendingUp} label="Laba kotor" value={formatCurrency(profit, true)} /><Stat icon={ShoppingBag} label="Unit terjual" value={formatNumber(units)} /><Stat icon={Boxes} label="Stok saat ini" value={`${formatNumber(product.stock)} ${product.unit}`} /></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.5fr_.8fr]"><section className="card min-w-0 p-5"><h2 className="font-extrabold text-slate-950 dark:text-white">Tren penjualan</h2><p className="mt-1 text-xs text-slate-500">24 transaksi penjualan terakhir</p><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ left: -20, right: 5 }}><defs><linearGradient id="productTrend" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={product.color} stopOpacity={.3}/><stop offset="100%" stopColor={product.color} stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4" opacity={.3}/><XAxis dataKey="date" tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#94a3b8" }} minTickGap={20}/><YAxis tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: "#94a3b8" }} tickFormatter={(value) => `${Number(value)/1000}k`}/><Tooltip formatter={(value) => formatCurrency(Number(value))}/><Area type="monotone" dataKey="omzet" stroke={product.color} strokeWidth={2.5} fill="url(#productTrend)"/></AreaChart></ResponsiveContainer></div></section><section className="card p-5"><h2 className="font-extrabold text-slate-950 dark:text-white">Informasi produk</h2><dl className="mt-5 divide-y divide-slate-100 text-sm dark:divide-slate-800"><Row label="Harga jual" value={formatCurrency(product.price)} /><Row label="Harga modal" value={formatCurrency(product.cost)} /><Row label="Margin / unit" value={formatCurrency(product.price - product.cost)} /><Row label="Batas stok" value={`${product.reorderPoint} ${product.unit}`} /><Row label="Estimasi margin" value={`${Math.round((product.price - product.cost) / product.price * 100)}%`} /></dl></section></div>
    <section className="card mt-5 overflow-hidden"><div className="p-5"><h2 className="font-extrabold text-slate-950 dark:text-white">Transaksi produk terbaru</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>ID</th><th>Tanggal</th><th>Kanal</th><th>Jumlah</th><th className="text-right">Total</th></tr></thead><tbody>{transactions.slice(0,12).map((item) => <tr key={item.id}><td className="font-bold">{item.id}</td><td>{formatDate(item.date, true)}</td><td>{item.channel}</td><td>{item.quantity} {product.unit}</td><td className="text-right font-extrabold">{formatCurrency(item.total)}</td></tr>)}</tbody></table></div></section></div>;
}

function Stat({ icon: Icon, label, value }: { icon: typeof Boxes; label: string; value: string }) { return <article className="card p-4"><Icon className="size-5 text-indigo-500"/><p className="mt-4 text-[11px] font-bold text-slate-500">{label}</p><p className="mt-1 truncate text-lg font-black text-slate-950 dark:text-white sm:text-xl">{value}</p></article>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 py-3"><dt className="text-slate-500">{label}</dt><dd className="font-extrabold text-slate-900 dark:text-white">{value}</dd></div>; }
